### ISSUE TITLE
DESCRIPTION file seems out of date

### ISSUE THREAD

**Issue by tomsing1** [csglab/GEDI#1]
Congrats on the GEDI publication! I noticed that the `DESCRIPTION` file seems out of date, e.g. the released source package is called version `1.0.0`, but the package is installed as version `0.0.0.9000`. There are a few other field that might need a bit more detail:

```
Package: GEDI
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person("First", "Last", , "first.last@example.com", role = c("aut", "cre"),
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
```

**Comment by arielmadr** [comment]
Thank you! 
I just updated the `DESCRIPTION `file and the released source package.
